/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'workType' : IDL.Text,
  'driverId' : IDL.Nat,
  'finalAmount' : IDL.Float64,
  'date' : IDL.Int,
  'hoursWorked' : IDL.Float64,
  'createdAt' : IDL.Int,
  'discountType' : IDL.Text,
  'acresWorked' : IDL.Float64,
  'tractorId' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'village' : IDL.Text,
  'notes' : IDL.Text,
  'advancePaid' : IDL.Float64,
  'discount' : IDL.Float64,
  'balanceDue' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'mobile' : IDL.Text,
  'rateType' : IDL.Text,
  'baseRate' : IDL.Float64,
});
export const CreditRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'lastPaymentDate' : IDL.Int,
  'totalDue' : IDL.Float64,
  'amountPaid' : IDL.Float64,
  'village' : IDL.Text,
  'notes' : IDL.Text,
  'mobile' : IDL.Text,
});
export const Driver = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalJobs' : IDL.Nat,
  'addedAt' : IDL.Int,
  'phone' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : IDL.Nat,
  'expenseType' : IDL.Text,
  'date' : IDL.Int,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'tractorId' : IDL.Opt(IDL.Nat),
  'amount' : IDL.Float64,
});
export const MaintenanceReminder = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Int,
  'description' : IDL.Text,
  'isDone' : IDL.Bool,
  'tractorId' : IDL.Nat,
  'reminderType' : IDL.Text,
});
export const Party = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'village' : IDL.Text,
  'phone' : IDL.Text,
});
export const Tractor = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'currentBookingId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'addedAt' : IDL.Int,
  'number' : IDL.Text,
});
export const DriverPerformance = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'totalJobs' : IDL.Nat,
});
export const MonthlyReport = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'totalJobs' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
});
export const PartyStats = IDL.Record({
  'totalJobs' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
  'udharBalance' : IDL.Float64,
});
export const Settings = IDL.Record({
  'hourlyRate' : IDL.Float64,
  'language' : IDL.Text,
  'darkMode' : IDL.Bool,
  'acreRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
  'createCreditRecord' : IDL.Func([CreditRecord], [IDL.Nat], []),
  'createDriver' : IDL.Func([Driver], [IDL.Nat], []),
  'createExpense' : IDL.Func([Expense], [IDL.Nat], []),
  'createMaintenanceReminder' : IDL.Func([MaintenanceReminder], [IDL.Nat], []),
  'createParty' : IDL.Func([Party], [IDL.Nat], []),
  'createTractor' : IDL.Func([Tractor], [IDL.Nat], []),
  'deleteBooking' : IDL.Func([IDL.Nat], [], []),
  'deleteCreditRecord' : IDL.Func([IDL.Nat], [], []),
  'deleteDriver' : IDL.Func([IDL.Nat], [], []),
  'deleteExpense' : IDL.Func([IDL.Nat], [], []),
  'deleteMaintenanceReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteParty' : IDL.Func([IDL.Nat], [], []),
  'deleteTractor' : IDL.Func([IDL.Nat], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCreditRecords' : IDL.Func([], [IDL.Vec(CreditRecord)], ['query']),
  'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllMaintenanceReminders' : IDL.Func(
      [],
      [IDL.Vec(MaintenanceReminder)],
      ['query'],
    ),
  'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
  'getAllTractors' : IDL.Func([], [IDL.Vec(Tractor)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByCustomerName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByDate' : IDL.Func([IDL.Int], [IDL.Vec(Booking)], ['query']),
  'getBookingsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCreditRecord' : IDL.Func([IDL.Nat], [CreditRecord], ['query']),
  'getDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
  'getDriverBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getDriverPerformance' : IDL.Func(
      [],
      [IDL.Vec(DriverPerformance)],
      ['query'],
    ),
  'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
  'getExpensesByMonth' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getMaintenanceReminder' : IDL.Func(
      [IDL.Nat],
      [MaintenanceReminder],
      ['query'],
    ),
  'getMonthlyReport' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyReport], ['query']),
  'getNetProfit' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
  'getParty' : IDL.Func([IDL.Nat], [Party], ['query']),
  'getPartyStats' : IDL.Func([IDL.Text], [PartyStats], ['query']),
  'getPendingCredits' : IDL.Func([], [IDL.Vec(CreditRecord)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTodayEarnings' : IDL.Func([IDL.Int], [IDL.Float64], ['query']),
  'getTractor' : IDL.Func([IDL.Nat], [Tractor], ['query']),
  'getTractorBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getUpcomingReminders' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(MaintenanceReminder)],
      ['query'],
    ),
  'updateBooking' : IDL.Func([IDL.Nat, Booking], [], []),
  'updateCreditRecord' : IDL.Func([IDL.Nat, CreditRecord], [], []),
  'updateDriver' : IDL.Func([IDL.Nat, Driver], [], []),
  'updateExpense' : IDL.Func([IDL.Nat, Expense], [], []),
  'updateMaintenanceReminder' : IDL.Func(
      [IDL.Nat, MaintenanceReminder],
      [],
      [],
    ),
  'updateParty' : IDL.Func([IDL.Nat, Party], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateTractor' : IDL.Func([IDL.Nat, Tractor], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'workType' : IDL.Text,
    'driverId' : IDL.Nat,
    'finalAmount' : IDL.Float64,
    'date' : IDL.Int,
    'hoursWorked' : IDL.Float64,
    'createdAt' : IDL.Int,
    'discountType' : IDL.Text,
    'acresWorked' : IDL.Float64,
    'tractorId' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'village' : IDL.Text,
    'notes' : IDL.Text,
    'advancePaid' : IDL.Float64,
    'discount' : IDL.Float64,
    'balanceDue' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'mobile' : IDL.Text,
    'rateType' : IDL.Text,
    'baseRate' : IDL.Float64,
  });
  const CreditRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'lastPaymentDate' : IDL.Int,
    'totalDue' : IDL.Float64,
    'amountPaid' : IDL.Float64,
    'village' : IDL.Text,
    'notes' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const Driver = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalJobs' : IDL.Nat,
    'addedAt' : IDL.Int,
    'phone' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : IDL.Nat,
    'expenseType' : IDL.Text,
    'date' : IDL.Int,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'tractorId' : IDL.Opt(IDL.Nat),
    'amount' : IDL.Float64,
  });
  const MaintenanceReminder = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Int,
    'description' : IDL.Text,
    'isDone' : IDL.Bool,
    'tractorId' : IDL.Nat,
    'reminderType' : IDL.Text,
  });
  const Party = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'village' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Tractor = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'currentBookingId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'addedAt' : IDL.Int,
    'number' : IDL.Text,
  });
  const DriverPerformance = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'totalJobs' : IDL.Nat,
  });
  const MonthlyReport = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'totalJobs' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
  });
  const PartyStats = IDL.Record({
    'totalJobs' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
    'udharBalance' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'hourlyRate' : IDL.Float64,
    'language' : IDL.Text,
    'darkMode' : IDL.Bool,
    'acreRate' : IDL.Float64,
  });
  
  return IDL.Service({
    'createBooking' : IDL.Func([Booking], [IDL.Nat], []),
    'createCreditRecord' : IDL.Func([CreditRecord], [IDL.Nat], []),
    'createDriver' : IDL.Func([Driver], [IDL.Nat], []),
    'createExpense' : IDL.Func([Expense], [IDL.Nat], []),
    'createMaintenanceReminder' : IDL.Func(
        [MaintenanceReminder],
        [IDL.Nat],
        [],
      ),
    'createParty' : IDL.Func([Party], [IDL.Nat], []),
    'createTractor' : IDL.Func([Tractor], [IDL.Nat], []),
    'deleteBooking' : IDL.Func([IDL.Nat], [], []),
    'deleteCreditRecord' : IDL.Func([IDL.Nat], [], []),
    'deleteDriver' : IDL.Func([IDL.Nat], [], []),
    'deleteExpense' : IDL.Func([IDL.Nat], [], []),
    'deleteMaintenanceReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteParty' : IDL.Func([IDL.Nat], [], []),
    'deleteTractor' : IDL.Func([IDL.Nat], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCreditRecords' : IDL.Func([], [IDL.Vec(CreditRecord)], ['query']),
    'getAllDrivers' : IDL.Func([], [IDL.Vec(Driver)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllMaintenanceReminders' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceReminder)],
        ['query'],
      ),
    'getAllParties' : IDL.Func([], [IDL.Vec(Party)], ['query']),
    'getAllTractors' : IDL.Func([], [IDL.Vec(Tractor)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByCustomerName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByDate' : IDL.Func([IDL.Int], [IDL.Vec(Booking)], ['query']),
    'getBookingsByStatus' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCreditRecord' : IDL.Func([IDL.Nat], [CreditRecord], ['query']),
    'getDriver' : IDL.Func([IDL.Nat], [Driver], ['query']),
    'getDriverBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getDriverPerformance' : IDL.Func(
        [],
        [IDL.Vec(DriverPerformance)],
        ['query'],
      ),
    'getExpense' : IDL.Func([IDL.Nat], [Expense], ['query']),
    'getExpensesByMonth' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getMaintenanceReminder' : IDL.Func(
        [IDL.Nat],
        [MaintenanceReminder],
        ['query'],
      ),
    'getMonthlyReport' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyReport],
        ['query'],
      ),
    'getNetProfit' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Float64], ['query']),
    'getParty' : IDL.Func([IDL.Nat], [Party], ['query']),
    'getPartyStats' : IDL.Func([IDL.Text], [PartyStats], ['query']),
    'getPendingCredits' : IDL.Func([], [IDL.Vec(CreditRecord)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTodayEarnings' : IDL.Func([IDL.Int], [IDL.Float64], ['query']),
    'getTractor' : IDL.Func([IDL.Nat], [Tractor], ['query']),
    'getTractorBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getUpcomingReminders' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(MaintenanceReminder)],
        ['query'],
      ),
    'updateBooking' : IDL.Func([IDL.Nat, Booking], [], []),
    'updateCreditRecord' : IDL.Func([IDL.Nat, CreditRecord], [], []),
    'updateDriver' : IDL.Func([IDL.Nat, Driver], [], []),
    'updateExpense' : IDL.Func([IDL.Nat, Expense], [], []),
    'updateMaintenanceReminder' : IDL.Func(
        [IDL.Nat, MaintenanceReminder],
        [],
        [],
      ),
    'updateParty' : IDL.Func([IDL.Nat, Party], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateTractor' : IDL.Func([IDL.Nat, Tractor], [], []),
  });
};

export const init = ({ IDL }) => { return []; };