/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : string,
  'workType' : string,
  'driverId' : bigint,
  'finalAmount' : number,
  'date' : bigint,
  'hoursWorked' : number,
  'createdAt' : bigint,
  'discountType' : string,
  'acresWorked' : number,
  'tractorId' : bigint,
  'totalAmount' : number,
  'village' : string,
  'notes' : string,
  'advancePaid' : number,
  'discount' : number,
  'balanceDue' : number,
  'paymentMode' : string,
  'mobile' : string,
  'rateType' : string,
  'baseRate' : number,
}
export interface CreditRecord {
  'id' : bigint,
  'customerName' : string,
  'lastPaymentDate' : bigint,
  'totalDue' : number,
  'amountPaid' : number,
  'village' : string,
  'notes' : string,
  'mobile' : string,
}
export interface Driver {
  'id' : bigint,
  'name' : string,
  'totalJobs' : bigint,
  'addedAt' : bigint,
  'phone' : string,
}
export interface DriverPerformance {
  'id' : bigint,
  'name' : string,
  'totalJobs' : bigint,
}
export interface Expense {
  'id' : bigint,
  'expenseType' : string,
  'date' : bigint,
  'createdAt' : bigint,
  'description' : string,
  'tractorId' : [] | [bigint],
  'amount' : number,
}
export interface MaintenanceReminder {
  'id' : bigint,
  'createdAt' : bigint,
  'dueDate' : bigint,
  'description' : string,
  'isDone' : boolean,
  'tractorId' : bigint,
  'reminderType' : string,
}
export interface MonthlyReport {
  'month' : bigint,
  'year' : bigint,
  'totalJobs' : bigint,
  'totalEarnings' : number,
}
export interface Party {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'village' : string,
  'phone' : string,
}
export interface PartyStats {
  'totalJobs' : bigint,
  'totalEarnings' : number,
  'udharBalance' : number,
}
export interface Settings {
  'hourlyRate' : number,
  'language' : string,
  'darkMode' : boolean,
  'acreRate' : number,
}
export interface Tractor {
  'id' : bigint,
  'status' : string,
  'currentBookingId' : [] | [bigint],
  'name' : string,
  'addedAt' : bigint,
  'number' : string,
}
export interface _SERVICE {
  'createBooking' : ActorMethod<[Booking], bigint>,
  'createCreditRecord' : ActorMethod<[CreditRecord], bigint>,
  'createDriver' : ActorMethod<[Driver], bigint>,
  'createExpense' : ActorMethod<[Expense], bigint>,
  'createMaintenanceReminder' : ActorMethod<[MaintenanceReminder], bigint>,
  'createParty' : ActorMethod<[Party], bigint>,
  'createTractor' : ActorMethod<[Tractor], bigint>,
  'deleteBooking' : ActorMethod<[bigint], undefined>,
  'deleteCreditRecord' : ActorMethod<[bigint], undefined>,
  'deleteDriver' : ActorMethod<[bigint], undefined>,
  'deleteExpense' : ActorMethod<[bigint], undefined>,
  'deleteMaintenanceReminder' : ActorMethod<[bigint], undefined>,
  'deleteParty' : ActorMethod<[bigint], undefined>,
  'deleteTractor' : ActorMethod<[bigint], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCreditRecords' : ActorMethod<[], Array<CreditRecord>>,
  'getAllDrivers' : ActorMethod<[], Array<Driver>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllMaintenanceReminders' : ActorMethod<[], Array<MaintenanceReminder>>,
  'getAllParties' : ActorMethod<[], Array<Party>>,
  'getAllTractors' : ActorMethod<[], Array<Tractor>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByCustomerName' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByDate' : ActorMethod<[bigint], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[string], Array<Booking>>,
  'getCreditRecord' : ActorMethod<[bigint], CreditRecord>,
  'getDriver' : ActorMethod<[bigint], Driver>,
  'getDriverBookings' : ActorMethod<[bigint], Array<Booking>>,
  'getDriverPerformance' : ActorMethod<[], Array<DriverPerformance>>,
  'getExpense' : ActorMethod<[bigint], Expense>,
  'getExpensesByMonth' : ActorMethod<[bigint, bigint], Array<Expense>>,
  'getMaintenanceReminder' : ActorMethod<[bigint], MaintenanceReminder>,
  'getMonthlyReport' : ActorMethod<[bigint, bigint], MonthlyReport>,
  'getNetProfit' : ActorMethod<[bigint, bigint], number>,
  'getParty' : ActorMethod<[bigint], Party>,
  'getPartyStats' : ActorMethod<[string], PartyStats>,
  'getPendingCredits' : ActorMethod<[], Array<CreditRecord>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTodayEarnings' : ActorMethod<[bigint], number>,
  'getTractor' : ActorMethod<[bigint], Tractor>,
  'getTractorBookings' : ActorMethod<[bigint], Array<Booking>>,
  'getUpcomingReminders' : ActorMethod<[bigint], Array<MaintenanceReminder>>,
  'updateBooking' : ActorMethod<[bigint, Booking], undefined>,
  'updateCreditRecord' : ActorMethod<[bigint, CreditRecord], undefined>,
  'updateDriver' : ActorMethod<[bigint, Driver], undefined>,
  'updateExpense' : ActorMethod<[bigint, Expense], undefined>,
  'updateMaintenanceReminder' : ActorMethod<
    [bigint, MaintenanceReminder],
    undefined
  >,
  'updateParty' : ActorMethod<[bigint, Party], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateTractor' : ActorMethod<[bigint, Tractor], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];