/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyReport {
    month: bigint;
    year: bigint;
    totalJobs: bigint;
    totalEarnings: number;
}
export interface Settings {
    hourlyRate: number;
    language: string;
    darkMode: boolean;
    acreRate: number;
}
export interface DriverPerformance {
    id: bigint;
    name: string;
    totalJobs: bigint;
}
export interface Tractor {
    id: bigint;
    status: string;
    currentBookingId?: bigint;
    name: string;
    addedAt: bigint;
    number: string;
}
export interface Party {
    id: bigint;
    name: string;
    createdAt: bigint;
    village: string;
    phone: string;
}
export interface Driver {
    id: bigint;
    name: string;
    totalJobs: bigint;
    addedAt: bigint;
    phone: string;
}
export interface CreditRecord {
    id: bigint;
    customerName: string;
    lastPaymentDate: bigint;
    totalDue: number;
    amountPaid: number;
    village: string;
    notes: string;
    mobile: string;
}
export interface MaintenanceReminder {
    id: bigint;
    createdAt: bigint;
    dueDate: bigint;
    description: string;
    isDone: boolean;
    tractorId: bigint;
    reminderType: string;
}
export interface Booking {
    id: bigint;
    customerName: string;
    status: string;
    workType: string;
    driverId: bigint;
    finalAmount: number;
    date: bigint;
    hoursWorked: number;
    createdAt: bigint;
    discountType: string;
    acresWorked: number;
    tractorId: bigint;
    totalAmount: number;
    village: string;
    notes: string;
    advancePaid: number;
    discount: number;
    balanceDue: number;
    paymentMode: string;
    mobile: string;
    rateType: string;
    baseRate: number;
}
export interface PartyStats {
    totalJobs: bigint;
    totalEarnings: number;
    udharBalance: number;
}
export interface Expense {
    id: bigint;
    expenseType: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    tractorId?: bigint;
    amount: number;
}
export interface backendInterface {
    createBooking(booking: Booking): Promise<bigint>;
    createCreditRecord(credit: CreditRecord): Promise<bigint>;
    createDriver(driver: Driver): Promise<bigint>;
    createExpense(expense: Expense): Promise<bigint>;
    createMaintenanceReminder(reminder: MaintenanceReminder): Promise<bigint>;
    createParty(party: Party): Promise<bigint>;
    createTractor(tractor: Tractor): Promise<bigint>;
    deleteBooking(id: bigint): Promise<void>;
    deleteCreditRecord(id: bigint): Promise<void>;
    deleteDriver(id: bigint): Promise<void>;
    deleteExpense(id: bigint): Promise<void>;
    deleteMaintenanceReminder(id: bigint): Promise<void>;
    deleteParty(id: bigint): Promise<void>;
    deleteTractor(id: bigint): Promise<void>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllCreditRecords(): Promise<Array<CreditRecord>>;
    getAllDrivers(): Promise<Array<Driver>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllMaintenanceReminders(): Promise<Array<MaintenanceReminder>>;
    getAllParties(): Promise<Array<Party>>;
    getAllTractors(): Promise<Array<Tractor>>;
    getBooking(id: bigint): Promise<Booking>;
    getBookingsByCustomerName(name: string): Promise<Array<Booking>>;
    getBookingsByDate(date: bigint): Promise<Array<Booking>>;
    getBookingsByStatus(status: string): Promise<Array<Booking>>;
    getCreditRecord(id: bigint): Promise<CreditRecord>;
    getDriver(id: bigint): Promise<Driver>;
    getDriverBookings(driverId: bigint): Promise<Array<Booking>>;
    getDriverPerformance(): Promise<Array<DriverPerformance>>;
    getExpense(id: bigint): Promise<Expense>;
    getExpensesByMonth(month: bigint, year: bigint): Promise<Array<Expense>>;
    getMaintenanceReminder(id: bigint): Promise<MaintenanceReminder>;
    getMonthlyReport(month: bigint, year: bigint): Promise<MonthlyReport>;
    getNetProfit(month: bigint, year: bigint): Promise<number>;
    getParty(id: bigint): Promise<Party>;
    getPartyStats(name: string): Promise<PartyStats>;
    getPendingCredits(): Promise<Array<CreditRecord>>;
    getSettings(): Promise<Settings>;
    getTodayEarnings(today: bigint): Promise<number>;
    getTractor(id: bigint): Promise<Tractor>;
    getTractorBookings(tractorId: bigint): Promise<Array<Booking>>;
    getUpcomingReminders(currentDate: bigint): Promise<Array<MaintenanceReminder>>;
    updateBooking(id: bigint, booking: Booking): Promise<void>;
    updateCreditRecord(id: bigint, credit: CreditRecord): Promise<void>;
    updateDriver(id: bigint, driver: Driver): Promise<void>;
    updateExpense(id: bigint, expense: Expense): Promise<void>;
    updateMaintenanceReminder(id: bigint, reminder: MaintenanceReminder): Promise<void>;
    updateParty(id: bigint, party: Party): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateTractor(id: bigint, tractor: Tractor): Promise<void>;
}
import type { Expense as _Expense, Tractor as _Tractor } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createBooking(arg0: Booking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createCreditRecord(arg0: CreditRecord): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCreditRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCreditRecord(arg0);
            return result;
        }
    }
    async createDriver(arg0: Driver): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDriver(arg0);
            return result;
        }
    }
    async createExpense(arg0: Expense): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createMaintenanceReminder(arg0: MaintenanceReminder): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMaintenanceReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMaintenanceReminder(arg0);
            return result;
        }
    }
    async createParty(arg0: Party): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParty(arg0);
            return result;
        }
    }
    async createTractor(arg0: Tractor): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTractor(to_candid_Tractor_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTractor(to_candid_Tractor_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteCreditRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCreditRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCreditRecord(arg0);
            return result;
        }
    }
    async deleteDriver(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriver(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async deleteMaintenanceReminder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMaintenanceReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMaintenanceReminder(arg0);
            return result;
        }
    }
    async deleteParty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteParty(arg0);
            return result;
        }
    }
    async deleteTractor(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTractor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTractor(arg0);
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllCreditRecords(): Promise<Array<CreditRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCreditRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCreditRecords();
            return result;
        }
    }
    async getAllDrivers(): Promise<Array<Driver>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDrivers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDrivers();
            return result;
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMaintenanceReminders(): Promise<Array<MaintenanceReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMaintenanceReminders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMaintenanceReminders();
            return result;
        }
    }
    async getAllParties(): Promise<Array<Party>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParties();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParties();
            return result;
        }
    }
    async getAllTractors(): Promise<Array<Tractor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTractors();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTractors();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return result;
        }
    }
    async getBookingsByCustomerName(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByCustomerName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByCustomerName(arg0);
            return result;
        }
    }
    async getBookingsByDate(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDate(arg0);
            return result;
        }
    }
    async getBookingsByStatus(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(arg0);
            return result;
        }
    }
    async getCreditRecord(arg0: bigint): Promise<CreditRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getCreditRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCreditRecord(arg0);
            return result;
        }
    }
    async getDriver(arg0: bigint): Promise<Driver> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriver(arg0);
            return result;
        }
    }
    async getDriverBookings(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverBookings(arg0);
            return result;
        }
    }
    async getDriverPerformance(): Promise<Array<DriverPerformance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDriverPerformance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDriverPerformance();
            return result;
        }
    }
    async getExpense(arg0: bigint): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_Expense_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_Expense_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesByMonth(arg0: bigint, arg1: bigint): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesByMonth(arg0, arg1);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesByMonth(arg0, arg1);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMaintenanceReminder(arg0: bigint): Promise<MaintenanceReminder> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceReminder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceReminder(arg0);
            return result;
        }
    }
    async getMonthlyReport(arg0: bigint, arg1: bigint): Promise<MonthlyReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyReport(arg0, arg1);
            return result;
        }
    }
    async getNetProfit(arg0: bigint, arg1: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getNetProfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNetProfit(arg0, arg1);
            return result;
        }
    }
    async getParty(arg0: bigint): Promise<Party> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return result;
        }
    }
    async getPartyStats(arg0: string): Promise<PartyStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartyStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartyStats(arg0);
            return result;
        }
    }
    async getPendingCredits(): Promise<Array<CreditRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingCredits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingCredits();
            return result;
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getTodayEarnings(arg0: bigint): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayEarnings(arg0);
            return result;
        }
    }
    async getTractor(arg0: bigint): Promise<Tractor> {
        if (this.processError) {
            try {
                const result = await this.actor.getTractor(arg0);
                return from_candid_Tractor_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTractor(arg0);
            return from_candid_Tractor_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTractorBookings(arg0: bigint): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTractorBookings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTractorBookings(arg0);
            return result;
        }
    }
    async getUpcomingReminders(arg0: bigint): Promise<Array<MaintenanceReminder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingReminders(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingReminders(arg0);
            return result;
        }
    }
    async updateBooking(arg0: bigint, arg1: Booking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBooking(arg0, arg1);
            return result;
        }
    }
    async updateCreditRecord(arg0: bigint, arg1: CreditRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCreditRecord(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCreditRecord(arg0, arg1);
            return result;
        }
    }
    async updateDriver(arg0: bigint, arg1: Driver): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDriver(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDriver(arg0, arg1);
            return result;
        }
    }
    async updateExpense(arg0: bigint, arg1: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(arg0, to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(arg0, to_candid_Expense_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMaintenanceReminder(arg0: bigint, arg1: MaintenanceReminder): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMaintenanceReminder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMaintenanceReminder(arg0, arg1);
            return result;
        }
    }
    async updateParty(arg0: bigint, arg1: Party): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(arg0, arg1);
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateTractor(arg0: bigint, arg1: Tractor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTractor(arg0, to_candid_Tractor_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTractor(arg0, to_candid_Tractor_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Expense_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Tractor_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tractor): Tractor {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    currentBookingId: [] | [bigint];
    name: string;
    addedAt: bigint;
    number: string;
}): {
    id: bigint;
    status: string;
    currentBookingId?: bigint;
    name: string;
    addedAt: bigint;
    number: string;
} {
    return {
        id: value.id,
        status: value.status,
        currentBookingId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.currentBookingId)),
        name: value.name,
        addedAt: value.addedAt,
        number: value.number
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseType: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    tractorId: [] | [bigint];
    amount: number;
}): {
    id: bigint;
    expenseType: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    tractorId?: bigint;
    amount: number;
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        tractorId: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.tractorId)),
        amount: value.amount
    };
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Tractor>): Array<Tractor> {
    return value.map((x)=>from_candid_Tractor_n10(_uploadFile, _downloadFile, x));
}
function to_candid_Expense_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Tractor_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tractor): _Tractor {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    expenseType: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    tractorId?: bigint;
    amount: number;
}): {
    id: bigint;
    expenseType: string;
    date: bigint;
    createdAt: bigint;
    description: string;
    tractorId: [] | [bigint];
    amount: number;
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        tractorId: value.tractorId ? candid_some(value.tractorId) : candid_none(),
        amount: value.amount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    currentBookingId?: bigint;
    name: string;
    addedAt: bigint;
    number: string;
}): {
    id: bigint;
    status: string;
    currentBookingId: [] | [bigint];
    name: string;
    addedAt: bigint;
    number: string;
} {
    return {
        id: value.id,
        status: value.status,
        currentBookingId: value.currentBookingId ? candid_some(value.currentBookingId) : candid_none(),
        name: value.name,
        addedAt: value.addedAt,
        number: value.number
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
